### ISSUE TITLE
Recording sample dual fisheye movies

### ISSUE THREAD

**Issue by kosso** [kfarr/theta-s-quartz#1]
Hi,
Great idea, trying to make a filter for Camtwist! 

This isn't an 'issue', more of a tip, in case you (or anyone reading this) didn't know : but you can use Quicktime to simply record the output of the ThetaS in live streaming mode. 
- Get Thetas S in live streaming mode. (Hold down power and mode button)
- _then_ plug in USB. 
- Open Quicktime. 
- File > New Movie Recording. 
- Click the down arrow next to the record button to pick the ThetaS
- Record! ;)

**Comment by kfarr** [comment]
Nice! Thanks for the tip. In fact, if you have camtwist running with the virtual camera you can first run the theta s through the filter in this repo and then use quicktime > new movie recording (and choose the virtual camera source) to record the output in realtime.
