### ISSUE TITLE
Add blending to edges of lenses

### ISSUE THREAD

**Issue by kfarr** [kfarr/theta-s-quartz#3]
Per @kosso, needs some sort of improved blending at the edges - improve borders between both using some sort of soft transition?

Also note that the [default theta s ER converter] DualFishBlender places the front image in the middle and split/spans the 'back' camera on either side.

**Comment by kosso** [comment]
One thing just occurred to me which might help here: The Paul Bourke code (I think) is assuming that each fisheye lens has a 180º field of view.  I have a feeling that the two Theta S lenses are 190º FOV. 

That would explain why the video output via Quartz seems to have some repetition at the edges. But this should also provide enough space to maybe apply an opacity vignette mask to help blend the images?

**Comment by kfarr** [comment]
You're totally right -- in fact here are a few words from Paul directly on this topic:
- There seems to be a tilt in the cameras, this is actually a good thing since it allows a better coverage and overlap at the north pole.
- After that, I suggest you need a good estimate for the FOV, I suspect it is around 185 degrees.
- Further improvement will be determining the radial dependence in fisheye space with latitude, the equations so far assume linear, that is rarely the case, the function tends to trail off near the extreme angles.

**Comment by kosso** [comment]
A quick search for "Ricoh Theta S field of view" throws out a few links which suggest it's 190.

eg : http://www.imaging-resource.com/PRODS/ricoh-theta-s/ricoh-theta-sA.HTM

I just tried editing your fish2sphere patches and edited the code in the settings panel in the Patch Inspector to change the FOV to 3.31613  - It's definitely starting to look more the desired/familiar output. 

;)

**Comment by kfarr** [comment]
Sweet, feel free to do a pull request or I'll play with that later tonight and commit those changes if I can get it working on my machine.

**Comment by kosso** [comment]
:+1:

**Comment by justibro** [comment]
I know it has been a while but I have recently worked on this and I have reworked a version to accommodate new sizes and blending but I do have an issue with the field of view and distance of objects from the camera.  Some may be able to help with that. https://github.com/justibro/theta-s-quartz/blob/master/theta-fish2sphere_J.qtz

**Comment by kfarr** [comment]
Added blended edges version from @justibro in https://github.com/kfarr/theta-s-quartz/commit/66b65dfad802f69d83e69ef874ae856e6d34f2ad
